### ISSUE TITLE
Architectural overview

### ISSUE THREAD

**Issue by severak** [bookdown/Bookdown.Bookdown#10]
I am planning to implement EPUB output for Bookdown.

I need to decide which classes to reuse and which to rewrite.

Can you provide some architectural overview to make my decisions easier?

**Comment by pmjones** [comment]
This is a fantastic idea. Before I dive too deep, can you tell me if you think it will be easier (1) to convert the end-result HTML to EPUB, or (2) to convert the Markdown to EPUB in stages like we covert to HTML now? (Hope that question made sense.)

**Comment by severak** [comment]
EPUB is basically HTML (+media and XML metadata) in special ZIP container.

So EPUB conversion occurs after HTML generation. But templates for HTML generation are EPUB-specific, because there is no need for on site navigation.

Hope you understanding.

**Comment by pmjones** [comment]
2 things, then:

First ,you will want to modify the templates used to generate the output. The originals are in the package `templates/` directory, but you can override those as described at http://bookdown.io/advanced/templates.html#3.3.1. You can remove the site navigation stuff in the `navheader.php` and `navfooter.php` templates.

Next, working with the HTML after conversion is going to be the tricky part. What happens internally is the Bookdown\Service\Processor applies a series of individual Process classes to a collection of Content objects to (1) convert them from Markdown to HTML; (2) read the headings, number them in the HTML, and retain them for TOC building; (3) build the TOC pages; and (4) render the HTML through the templates.

So you will want to create a new Bookdown\Process\Process, one that occurs after the final rendering, and do your EPUB conversions there. You can do that by modifying the Bookdown\Service\ProcessorBuilder to tack your EpubProcess on to the end.

Of course, that means modifying the codebase directly, which is probably not what we want in the long term. But in the short term it will let you build something that works. Later, we can address how to build in a command switch `--format=epub` that swaps between EPUB and plain old HTML.

I know that's a lot to take in; please let me know if you have any questions. And thanks a ton for your interest and assistance!

**Comment by severak** [comment]
OK. I will create modified copy of bookdown.

When it's working well, I will let you know.

Thanks for cooperation.
