### ISSUE TITLE
Rendering Bash file scripts

### ISSUE THREAD

**Issue by harikt** [bookdown/Bookdown.Bookdown#12]
This is with respect to issue opened at  https://github.com/thephpleague/commonmark/issues/173 .

So far it seems the issue with DomDocument . The comments are true I believe http://php.net/manual/en/class.domdocument.php#96709

**Comment by colinodell** [comment]
Essentially there seems to be an issue with `HeadingsProcess` garbling certain characters.  My hunch is that `DomDocument` isn't using UTF-8 to load and/or save the HTML.

**Comment by pmjones** [comment]
Closed per #13
