### ISSUE TITLE
Support for HTML base path

### ISSUE THREAD

**Issue by sandrokeil** [bookdown/Bookdown.Bookdown#15]
I've a problem with directories in the URL. The generated HTML link is absolute beginning with a _/_. Is it possible to add a bookdown.json config entry called `base-path` which writes in the HTML header the base path entry or is there a other solution?

``` html
<html>
  <head>
    <base href="http://sandrokeil.github.io/interop-config/">
  </head>
</html>
```

Here is the [example page](http://sandrokeil.github.io/interop-config/).

**Comment by sandrokeil** [comment]
@pmjones I've committed the [wanted HTML result](https://github.com/sandrokeil/interop-config/commit/1c32740d5ec1d23d404f117d78061f3ebe6dd3be#diff-4d4ae5806e55eb94637fcaeae0ff9c2b) to my GitHub pages.

**Comment by pmjones** [comment]
This is a good idea. If you can come up with a PR for it, I can review.

At first glance, it seems like the root-level config entry ought to be `base` or `baseHref`, and its default value should be `/`. All generated links should then have the leading `/` stripped from them. But that's just an initial intuition.

**Comment by pmjones** [comment]
Hm, is it possible to have the base-href *not* include the trailing slash? Then we would not need to strip the leading slash from the generated links.

**Comment by pmjones** [comment]
Gah! It turns out this is already there, kind of. You can set `rootHref` in the config, and it will get added to every generated link. Cf. https://github.com/bookdown/Bookdown.Bookdown/blob/master/src/Config/RootConfig.php#L66-L71 . Clearly I need to document that.

Having said that, if you think a `baseHref` makes more sense, let me know.

**Comment by sandrokeil** [comment]
This works for me. Please add this to the documentation.
