### ISSUE TITLE
TOC depth limit status

### ISSUE THREAD

**Issue by sandrokeil** [bookdown/Bookdown.Bookdown#21]
How is the status of the TOC depth limit? There exists a branch but it's currently not implemented or?

**Comment by pmjones** [comment]
Stalled, and no implementation that I recall. Please work on it, if you feel so inclined. :-)

**Comment by pmjones** [comment]
Incidentally, I just added you as a "write" collaborator on this repo. With great power comes great responsibility ;-)

**Comment by sandrokeil** [comment]
@pmjones Thanks for your trust. :-)

**Comment by sandrokeil** [comment]
See #22
