### ISSUE TITLE
TocDepth not working properly?

### ISSUE THREAD

**Issue by pmjones** [bookdown/Bookdown.Bookdown#35]
@sandrokeil When I set `"tocDepth": 1`, at the root level, then I correctly see only one level of TOC depth at the root.

However, when I set it to 2 at the root level, I see all levels of TOC depth at the root.

This is in the bookdown.github.io `develop` branch.

I looked for, but did not see, a test for the tocDepth stuff, so that may be needed.

Thoughts?

**Comment by sandrokeil** [comment]
@pmjones Oh no, you're right. Something goes wrong. I will ckeck this and add a test for this issue. Sorry.

**Comment by pmjones** [comment]
Fixed by #36.
