### ISSUE TITLE
How to add content search like lunr.js?

### ISSUE THREAD

**Issue by tobiju** [bookdown/Bookdown.Bookdown#41]
I would like to implement a documentation search mechanism like lunr.js. Lunr is base on a json file which holds the index. I think we can implement an json processor to generate the index for every book. Frontend stuff could be implemented in tobiju/bookdown-bootswatch-templates.  Do you have any suggestions to that?

**Comment by pmjones** [comment]
If I understand correctly, it seems like you would want to create a new Process (cf. src\Process) to create an indexing process for the system. You'd then need to modify the RootConfig to allow for it, and the ProcessorBuilder to apply it. I know that sounds like a lot; let me know as you have further more-specific questions.

**Comment by tobiju** [comment]
@pmjones I did that already here https://github.com/tobiju/Bookdown.Bookdown/tree/search. The question is now, do we need this functionality in the main bookdown project or should I put this stuff at my tobiju/bookdown-bootswatch-templates as custom processor.

**Comment by pmjones** [comment]
@tobiju (/me ponders)

Perhaps the thing to do is add an "indexing" process, and have your work be the default?

This also makes me think that the Process listings might need to become more generic, somehow, and allow people to add their own processes to the queue of processors.

**Comment by tobiju** [comment]
An general index process is a good idea. This seems to be really easy to realise. A solution for me atm was to override your conversion process per bookdown.json conversionProcess key. This works great, but seems to bee just a temporary solution. I think the possibility to search a documentation is minimum requirement and makes bookdown more interessting. If you are interested how the search could work you can checkout my templates https://github.com/tobiju/bookdown-bootswatch-templates.git development branch and add my conversion process to your bookdown.json "conversionProcess": "Tobiju\Bookdown\Process\Conversion\ConversionProcessBuilder".

**Comment by sandrokeil** [comment]
> allow people to add their own processes to the queue of processors.

This is really an interesting idea. In this case the raw Markdown files are used. Not sure how the interface looks like. Someone need raw Markdown files and others maybe the DomDocument.

Or do you mean to add a queue for every process like the index process?

**Comment by tobiju** [comment]
I think it would be a good idea to add a queue mechanism for every kind of process.

**Comment by pmjones** [comment]
@tobiju Let's consider the queue mechanism after adding the indexing process. Changing the queue mechanism is relatively big, whereas adding the new process is relatively small.

@sandrokeil I mean adding a way for users to specify which processes should be applied, and in which order, via bookdown.json. That may or may not be wise, but I think it bears consideration.

**Comment by sandrokeil** [comment]
@pmjones That's really interesting and would be an awesome feature. Maybe like pipes in unix.

**Comment by tobiju** [comment]
Maybe it is a good idea to write a commonmark plugin to have more flexibility to build the search index? I will check this.

@pmjones this seems not to work, because I don't have a reference to the html file.

**Comment by sandrokeil** [comment]
@tobiju Is this issue still valid?
