### ISSUE TITLE
Add to staticgen.com

### ISSUE THREAD

**Issue by jakejohns** [bookdown/Bookdown.Bookdown#46]
I was messing around with static generation stuff, and ran across this:
http://www.staticgen.com/

I was [about to add bookdown](https://github.com/netlify/staticgen/compare/master...jakejohns:project/bookdown), but I thought I'd ask first before randomly promoting your project on some random site.

Any reason I shouldn't?

**Comment by sandrokeil** [comment]
@pmjones What do you think?

**Comment by pmjones** [comment]
Send it!

(To be clear, that's a "yes, add it to staticgen." :-)

**Comment by jakejohns** [comment]
alright, cool. done!

**Comment by jakejohns** [comment]
http://www.staticgen.com/bookdown_php
There was a naming conflict with the R project
