### ISSUE TITLE
Any option to disable rendering of heading numbers?

### ISSUE THREAD

**Issue by nasko** [bookdown/Bookdown.Bookdown#47]
Sorry for submitting an issue for this, but I couldn't think of any other way to ask - is there any way to configure the headings to not be rendered with their respective numbers?

I browsed the default templates and figured that by using my own version of `toc.php` I could render the TOC entries without numbers, but what about the inline headings - those rendered in the page content?

**Comment by sandrokeil** [comment]
@nasko Currently we have no option available for that. For a quick workaround, you can define your own [HeadingsProces](https://github.com/bookdown/Bookdown.Bookdown/blob/1.x/src/Process/Headings/HeadingsProcess.php) class and override the `addHeading()` method. Take a look at this [config file](https://github.com/bookdown/Bookdown.Bookdown/blob/1.x/tests/Config/RootConfigTest.php#L18). 

BTW it's on the TODO list if you want to contribute. :smile: 

Maybe we can write a [CommonMark BlockRenderer](http://commonmark.thephpleague.com/customization/block-rendering/) for the headings to make this extensible/configureable. /cc @tobiju @pmjones

**Comment by codeliner** [comment]
Fixed by #56, right?

**Comment by sandrokeil** [comment]
Yes, it can be disabled by adding this option to the `bookdown.json`.

```json
{
  "numbering": false
}
```

**Comment by BruceKendall** [comment]
I am trying to apply this as a user -- where does the bookdown.json file live? I tried putting it (with the above text) in the directory with my Rmd files, but it had no impact.

I'm using version 0.3.17 from CRAN.

**Comment by jakejohns** [comment]
@BruceKendall I believe you're looking for the R project: https://github.com/rstudio/bookdown

**Comment by sandrokeil** [comment]
@BruceKendall I don't know what you mean with

> I'm using version 0.3.17 from CRAN.

But you find an example [here](https://github.com/sandrokeil/interop-config/blob/master/doc/bookdown.json#L10).

**Comment by BruceKendall** [comment]
My mistake - I am in fact looking for the R project and didn't realize this was something different (google search led me to this thread...)

Apologies for the distraction!
