### ISSUE TITLE
Q: template value

### ISSUE THREAD

**Issue by basz** [bookdown/Bookdown.Bookdown#49]
Is is possible to define a template value where a token is replaced in renders?

eg. 

variable

```
$SERVER_URI = 'example.com';
```

template:

```
Our server is available at http://{$SERVER_URI}/some/path
```

renders as:

```
<p>Our server is available at http://example.com/some/path</p>
```

**Comment by sandrokeil** [comment]
The server URI can be configured via [the config file](https://github.com/bookdown/Bookdown.Bookdown/blob/1.x/tests/Config/RootConfigTest.php#L22). You can also override/configure the `renderingProcess`. It is possible to only [override a part of the original template](http://bookdown.io/advanced/templates.html#3.4.1). In our [bootswatch template](https://github.com/tobiju/bookdown-bootswatch-templates) we use env variables, but you have to use your own template.

I hope one of this helps you. :-)

**Comment by basz** [comment]
Well, I did not mean to change the server url of the book. I wish to replace a token (in my example a SERVER_URI) not inside the template but inside the markdown content.

**Comment by sandrokeil** [comment]
Alright, then you can try to write your own renderer and replace your [tokens here](https://github.com/bookdown/Bookdown.Bookdown/blob/1.x/src/Process/Rendering/RenderingProcess.php#L33).
