### ISSUE TITLE
Content order in bookdown.json

### ISSUE THREAD

**Issue by severak** [bookdown/Bookdown.Bookdown#5]
It seems that structure of `bookdown.json` is little bit broken. The order of  content items may be unspecified, when it's read by something other than php.

To cite [specification](http://www.json.org/):

> An object is an unordered set of name/value pairs.

**Comment by pmjones** [comment]
The perils of using PHP, which does always return them in the same order. But you're right about the specification saying that object values are unordered; I'll have to modify the format. Thanks!

**Comment by pmjones** [comment]
@severak Please see PR #8 for a solution to this. Your thoughts are welcome.

**Comment by severak** [comment]
It seems to be good solution.

**Comment by pmjones** [comment]
Fixed by #8
