### ISSUE TITLE
Is there a 1.0.0-beta2 already planned ?

### ISSUE THREAD

**Issue by llaville** [bookdown/Bookdown.Bookdown#59]
Hello,

I want to known, if there is a beta2 planned to be release. 

I've, another time fell in that trap again. See my contrib about image not available https://github.com/bookdown/Bookdown.Bookdown/pull/50

Thanks in advance

**Comment by pmjones** [comment]
Funny, I was thinking just yesterday that, after PRs #58  and #57 , perhaps another release is warranted.

@sandrokeil your thoughts?

**Comment by sandrokeil** [comment]
@pmjones Yes, I guess it's release time. :-)

**Comment by llaville** [comment]
Any new about a planned release ?

**Comment by pmjones** [comment]
@llaville Yes -- unless @sandrokeil or others have objections, I am preparing a stable release for today or tomorrow. :-)

**Comment by llaville** [comment]
Really nice to heard :) I'll have a look as soon as it will be released !

**Comment by pmjones** [comment]
@llaville A couple days later than hoped, but still: released! https://github.com/bookdown/Bookdown.Bookdown/releases/tag/1.0.0

**Comment by llaville** [comment]
Thanks; Will have a look on it !
