### ISSUE TITLE
Table and Figure caption not showing Bengali characters

### ISSUE THREAD

**Issue by raheems** [bookdown/Bookdown.Bookdown#61]
I am testing the bookdown-demo-master to see if a Bengali books can be written with bookdown. One issue I see is the caption of Fables and Figures. Non-English characters do not show up in the produced html file.

```
{r nice-tab, tidy=FALSE}
knitr::kable(
  head(iris, 20), caption = 'The বাংলায় ক্যাপশন হচ্ছে কিনা পরীক্ষা করছি!',
  booktabs = TRUE
)
```

When I run this, the output only shows  "The !" in the caption of the table. That is it ignores the Bengali text completely. This is happening with Figure captions as well. Is there anything that I need to change to fix this? Thank you.

**Comment by sandrokeil** [comment]
@raheems Looks like you are on the wrong project? We don't have a `bookdown-demo` project? Do you mean [rstudio/bookdown-demo](https://github.com/rstudio/bookdown-demo)?

**Comment by raheems** [comment]
My apologies. Thanks for your note. However, isn't the issue related to bookdown in general? I've now posted it in the repository you've mentioned. Thanks.

**Comment by pmjones** [comment]
@raheems Is this still an issue for you? I believe we have added some mbstring conversions since your initial report, which may fix the problem.

**Comment by raheems** [comment]
I've switched to mac and it was not an issue there :)
