### ISSUE TITLE
PHP 7.2 count issue

### ISSUE THREAD

**Issue by sandrokeil** [bookdown/Bookdown.Bookdown#71]
There is a small bug with PHP 7.2 `PHP Warning:  count(): Parameter must be an array or an object that implements Countable in src/Content/TocHeading.php on line 47`

**Comment by pmjones** [comment]
Hi @sandrokeil -- is this still an issue?

**Comment by sandrokeil** [comment]
I will close it for now and will reopen it if I encounter this problem again.
